Fix circular import
Error while finding module specification for 'tagall_bot.__main__' (ImportError: cannot import name 'DB_URI' from partially initialized module 'tagall_bot' (most likely due to a circular import) (/app/tagall_bot/__init__.py))

Signed-off-by: Harsh Navdhare <navdhareharsh2001@gmail.com>